---

- name: Install Keepalived when HA mode is enabled
  ansible.builtin.include_tasks: keepalived.yml
  when:
    - rke2_api_ip is defined
    - inventory_hostname in groups[rke2_servers_group_name]
    - rke2_ha_mode | bool
    - rke2_ha_mode_keepalived | bool

- name: Download and install RKE2 {{ rke2_version }}
  ansible.builtin.include_tasks: rke2.yml

- name: CIS Hardening
  ansible.builtin.include_tasks: cis.yml
  when:
    - rke2_cis_profile | length > 0

- name: Find Active Server
  ansible.builtin.include_tasks: find_active_server.yml

- name: Enable IPVS kernel module
  community.general.modprobe:
    name: ip_vs
    state: present
    persistent: present
  when:
    - rke2_kubevip_ipvs_lb_enable | bool
    - inventory_hostname in groups[rke2_servers_group_name]
    - rke2_ha_mode | bool
    - rke2_ha_mode_kubevip | bool
    - not rke2_ha_mode_keepalived | bool


- name: Copy kube-vip manifests to the masternode
  ansible.builtin.include_tasks: kubevip.yml
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0
    - rke2_ha_mode | bool
    - rke2_ha_mode_kubevip | bool
    - not rke2_ha_mode_keepalived | bool

- name: Copy ingress-nginx manifests to the masternode
  ansible.builtin.include_tasks: ingress-nginx.yml
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0
    - rke2_ingress_nginx_values is defined
    - rke2_ingress_nginx_values | length > 0

- name: Prepare very first server node in the cluster
  ansible.builtin.include_tasks: first_server.yml
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0
    - active_server is not defined

- name: Restore etcd specific tasks
  ansible.builtin.include_tasks: first_server_restore.yml
  when:
    - active_server is defined
    - inventory_hostname == active_server or inventory_hostname == groups[rke2_servers_group_name].0
    - do_etcd_restore is defined or do_etcd_restore_from_s3 is defined

- name: Prepare and join remaining nodes of the cluster
  ansible.builtin.include_tasks: remaining_nodes.yml
  when:
    - active_server is defined
    - groups[rke2_cluster_group_name] | length | int >= 2

- name: Rolling cordon and drain restart when version changes
  ansible.builtin.include_tasks: rolling_restart.yml
  with_items: "{{ groups[rke2_cluster_group_name] }}"
  loop_control:
    loop_var: _host_item
  when:
    - hostvars[_host_item].inventory_hostname == inventory_hostname
    - installed_version is defined
    - installed_version != "not installed"
    - rke2_version is defined
    - rke2_version != running_version

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Rolling restart when config files change
  ansible.builtin.include_tasks: change_config.yml
  with_items: "{{ groups[rke2_cluster_group_name] }}"
  loop_control:
    loop_var: _host_item
  when:
    - hostvars[_host_item].inventory_hostname == inventory_hostname
    - rke2_restart_needed

- name: Final steps
  ansible.builtin.include_tasks: summary.yml

- block:
    - name: Install iscsi utils
      dnf:
        name: "iscsi-initiator-utils"
      become: true
    
    - name: Restart iscsid
      systemd:
        name: iscsid
        state: started
        enabled: true
  when: enable_longhorn

- block:
    - name: Copy nerdctl tarball
      copy:
        src: "nerdctl-linux-amd64.tar.gz"
        dest: "/tmp/nerdctl-linux-amd64.tar.gz"
        mode: "0755"
    
    - name: Extract nerdctl tarball
      command: "tar Cxzvvf /usr/local/bin /tmp/nerdctl-linux-amd64.tar.gz"

    - name: Ensure the alias is in .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "alias nerdctl='nerdctl -a /run/k3s/containerd/containerd.sock -n k8s.io'"
        state: present

    - name: Ensure export ENV
      lineinfile:
        path: ~/.bashrc
        line: "export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml"
        state: present

- block:
    - name: Set working directory
      set_fact:
        chart_dir: "{{ playbook_dir }}/roles/rke2/files"

    - name: Create service file
      copy:
        dest: /etc/systemd/system/chart-server.service
        content: |
          [Unit]
          Description=Simple HTTP Server for chart repo

          [Service]
          ExecStart=/usr/bin/python3 -m http.server {{ chart_repo_port }}
          WorkingDirectory={{ chart_dir }}
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      ansible.builtin.systemd:
        name: systemd
        daemon_reload: yes

    - name: Enable and start chart-server service
      ansible.builtin.systemd:
        name: chart-server
        enabled: yes
        state: started
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0

- name: Extra installation
  ansible.builtin.include_tasks: extra.yml
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0

